### ISSUE TITLE
ore generation is too aggressive

### ISSUE THREAD

**Issue by codec-d** [jdawg3636/ICBM#4]
sulfur overtakes gold in my world seed and is easily one of the most common ores

**Comment by jdawg3636** [comment]
This is already user-configurable. See `oreSulfurSize`, `oreSulfurRange`, and `oreSulfurCount` in your `config/intercontinentalballisticredux-common.toml` file.

As for the current default values, I've had no issue. I just ran a test, and in a 3x3 chunk area WorldEdit counted 89 gold ore, 25 diamond ore, and 42 uranium ore. This is, of course, drastically less than the 1761 sulfur ore in the same area, but it shows that sulfur ore is not prohibiting others from generating, and is (as intended) basically replacing stone near bedrock.

If you prefer a different generation pattern, I encourage you to tweak the aforementioned parameters 👍
