### ISSUE TITLE
launch platform shows up as peripheral in computercraft, but can't be used

### ISSUE THREAD

**Issue by dkmk100** [jdawg3636/ICBM#6]
it has no methods other than the standard inventory ones...

**Comment by dkmk100** [comment]
![image](https://user-images.githubusercontent.com/33072952/201500444-c291be1a-e9dd-4aa2-bf00-c04ae57835d5.png)

**Comment by jdawg3636** [comment]
What version of Minecraft are you playing on? This repository is for Intercontinental Ballistic Redux, a rewrite of the mod for Minecraft 1.16.5+. It does not currently have any support for ComputerCraft, so I highly doubt that it would show up as a peripheral at all.

If you're playing on Minecraft 1.12.2 or below, then that's a separate project ([https://github.com/BuiltBrokenModding/ICBM-Classic/tree/prod/1.12](https://github.com/BuiltBrokenModding/ICBM-Classic/tree/prod/1.12)). I don't think they support ComputerCraft either, but I could be wrong.

Most of the devices in both mods can be controlled using redstone and can interact with hoppers, item conduits, etc., so it shouldn't be too difficult for ComputerCraft to control them indirectly. If there's something specific that you're trying to accomplish, I would recommend asking around in my Discord server ;) [https://discord.gg/7wZzJTC](https://discord.gg/7wZzJTC)
